# Generated by Django 4.2.2 on 2023-11-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bloog_group',
            new_name='blood_group',
        ),
    ]
