# Generated by Django 4.2.2 on 2023-11-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_rename_bloog_group_userprofile_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
