# Generated by Django 4.2.2 on 2023-11-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_remove_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.DecimalField(decimal_places=12, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lon',
            field=models.DecimalField(decimal_places=12, max_digits=22, null=True),
        ),
    ]
